# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageToPdfWindow(object):
    def setupUi(self, ImageToPdfWindow):
        ImageToPdfWindow.setObjectName("ImageToPdfWindow")
        ImageToPdfWindow.resize(454, 322)
        ImageToPdfWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(ImageToPdfWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectFoldButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFoldButton.setGeometry(QtCore.QRect(330, 30, 113, 32))
        self.selectFoldButton.setObjectName("selectFoldButton")
        self.foldEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.foldEdit.setGeometry(QtCore.QRect(40, 30, 261, 31))
        self.foldEdit.setReadOnly(True)
        self.foldEdit.setObjectName("foldEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.label.setObjectName("label")
        self.scaleEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.scaleEdit.setGeometry(QtCore.QRect(120, 80, 51, 21))
        self.scaleEdit.setObjectName("scaleEdit")
        self.fillBox = QtWidgets.QCheckBox(self.centralwidget)
        self.fillBox.setGeometry(QtCore.QRect(30, 110, 331, 20))
        self.fillBox.setChecked(True)
        self.fillBox.setObjectName("fillBox")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(150, 260, 131, 51))
        self.startButton.setObjectName("startButton")
        self.autoScaleEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.autoScaleEdit.setGeometry(QtCore.QRect(370, 110, 71, 21))
        self.autoScaleEdit.setObjectName("autoScaleEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(30, 150, 321, 79))
        self.textEdit.setObjectName("textEdit")
        ImageToPdfWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImageToPdfWindow)
        QtCore.QMetaObject.connectSlotsByName(ImageToPdfWindow)

    def retranslateUi(self, ImageToPdfWindow):
        _translate = QtCore.QCoreApplication.translate
        ImageToPdfWindow.setWindowTitle(_translate("ImageToPdfWindow", "MainWindow"))
        self.selectFoldButton.setText(_translate("ImageToPdfWindow", "选择目录"))
        self.label.setText(_translate("ImageToPdfWindow", "图片缩放比例"))
        self.scaleEdit.setText(_translate("ImageToPdfWindow", "1.5"))
        self.fillBox.setText(_translate("ImageToPdfWindow", "当页面底部有空白区域时，是否尽量填充,缩放值设置"))
        self.startButton.setText(_translate("ImageToPdfWindow", "开始"))
        self.autoScaleEdit.setText(_translate("ImageToPdfWindow", "1.7"))
        self.textEdit.setHtml(_translate("ImageToPdfWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">说明：目录中只能有png，jpg，jpeg的图片。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">排序规则，是把文件名转为数字进行排序。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">例如：1_1.png，2.png，2_1.png，2_3.png</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImageToPdfWindow = QtWidgets.QMainWindow()
    ui = Ui_ImageToPdfWindow()
    ui.setupUi(ImageToPdfWindow)
    ImageToPdfWindow.show()
    sys.exit(app.exec_())
