# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MergeFileSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 0, 60, 16))
        self.label.setObjectName("label")
        self.deleteBtnView = QtWidgets.QPushButton(Dialog)
        self.deleteBtnView.setGeometry(QtCore.QRect(260, 240, 151, 51))
        self.deleteBtnView.setObjectName("deleteBtnView")
        self.splitBtnView = QtWidgets.QPushButton(Dialog)
        self.splitBtnView.setGeometry(QtCore.QRect(340, 150, 81, 31))
        self.splitBtnView.setObjectName("splitBtnView")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 411, 91))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.startPosEditView = QtWidgets.QLineEdit(Dialog)
        self.startPosEditView.setGeometry(QtCore.QRect(10, 150, 113, 21))
        self.startPosEditView.setObjectName("startPosEditView")
        self.endPosEditView = QtWidgets.QLineEdit(Dialog)
        self.endPosEditView.setGeometry(QtCore.QRect(140, 150, 113, 21))
        self.endPosEditView.setObjectName("endPosEditView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "高级设置"))
        self.deleteBtnView.setText(_translate("Dialog", "移除本PDF"))
        self.splitBtnView.setText(_translate("Dialog", "设置"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">设置开始和结束的页位置。合并时，只使用这区间内的PDF进行合并。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果只设置开始位置，那么就从开始位置开始的PDF进行合并。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">页数从1开始算起</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.startPosEditView.setPlaceholderText(_translate("Dialog", "开始位置"))
        self.endPosEditView.setPlaceholderText(_translate("Dialog", "结束位置"))
