# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MergeFileItemView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(605, 52)
        self.moreBtnView = QtWidgets.QPushButton(Form)
        self.moreBtnView.setGeometry(QtCore.QRect(530, 10, 71, 31))
        self.moreBtnView.setObjectName("moreBtnView")
        self.upBtnView = QtWidgets.QPushButton(Form)
        self.upBtnView.setGeometry(QtCore.QRect(450, 10, 81, 31))
        self.upBtnView.setObjectName("upBtnView")
        self.downBtnView = QtWidgets.QPushButton(Form)
        self.downBtnView.setGeometry(QtCore.QRect(360, 10, 91, 31))
        self.downBtnView.setObjectName("downBtnView")
        self.fileNameTitleLabel = QtWidgets.QLabel(Form)
        self.fileNameTitleLabel.setGeometry(QtCore.QRect(10, 10, 60, 16))
        self.fileNameTitleLabel.setObjectName("fileNameTitleLabel")
        self.fileNameLabelView = QtWidgets.QTextEdit(Form)
        self.fileNameLabelView.setEnabled(False)
        self.fileNameLabelView.setGeometry(QtCore.QRect(60, 0, 291, 41))
        self.fileNameLabelView.setReadOnly(True)
        self.fileNameLabelView.setObjectName("fileNameLabelView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.moreBtnView.setText(_translate("Form", "更多"))
        self.upBtnView.setText(_translate("Form", "上移"))
        self.downBtnView.setText(_translate("Form", "下移"))
        self.fileNameTitleLabel.setText(_translate("Form", "文件名："))
        self.fileNameLabelView.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.fileNameLabelView.setPlaceholderText(_translate("Form", "阿斯顿发斯蒂芬阿斯顿发斯蒂芬阿萨德处罚asdfasdfasdfasdfasdfasdfa asdfasdf s适当阿斯顿发送到啊撒大声地阿斯顿发送"))
