# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MergePdfWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainPage)
        self.centralwidget.setObjectName("centralwidget")
        self.addBtnView = QtWidgets.QPushButton(self.centralwidget)
        self.addBtnView.setGeometry(QtCore.QRect(370, 60, 113, 32))
        self.addBtnView.setObjectName("addBtnView")
        self.exportBtnView = QtWidgets.QPushButton(self.centralwidget)
        self.exportBtnView.setGeometry(QtCore.QRect(490, 410, 113, 32))
        self.exportBtnView.setObjectName("exportBtnView")
        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 110, 601, 291))
        self.listView.setObjectName("listView")
        self.savePathTextView = QtWidgets.QLineEdit(self.centralwidget)
        self.savePathTextView.setEnabled(True)
        self.savePathTextView.setGeometry(QtCore.QRect(30, 10, 321, 31))
        self.savePathTextView.setReadOnly(True)
        self.savePathTextView.setObjectName("savePathTextView")
        self.setSavePathBtnView = QtWidgets.QPushButton(self.centralwidget)
        self.setSavePathBtnView.setGeometry(QtCore.QRect(370, 10, 113, 32))
        self.setSavePathBtnView.setObjectName("setSavePathBtnView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 191, 16))
        self.label.setObjectName("label")
        MainPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "MainWindow"))
        self.addBtnView.setText(_translate("MainPage", "添加"))
        self.exportBtnView.setText(_translate("MainPage", "生成"))
        self.savePathTextView.setPlaceholderText(_translate("MainPage", "设置保存目录"))
        self.setSavePathBtnView.setText(_translate("MainPage", "设置"))
        self.label.setText(_translate("MainPage", "添加要合并的PDF"))
